name: fyp
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4


#------------------ PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.3.0
  intl: ^0.20.1
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  connectivity_plus: ^6.1.2
  lottie: ^3.2.0
  share_plus: ^11.1.0
  uuid: ^4.2.1
  path_provider: ^2.1.1
  crypto: ^3.0.7
  flutter_dotenv: ^6.0.0
  ntp: ^2.0.0

  # Image & Video Processing
  image: ^4.5.4
  image_picker: ^1.2.0
  photo_view: ^0.15.0
  camera: ^0.10.5+1
  video_player: ^2.10.0
  video_compress: ^3.1.4
  flutter_image_compress: ^2.4.0
  permission_handler: ^12.0.1

  # OTP Text Field
  flutter_otp_text_field: ^1.4.0+2

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_core_platform_interface: ^6.0.0
  cloud_firestore: ^6.0.0
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3

  # Notification
  flutter_local_notifications: ^19.5.0

  # Deep Link
  app_links: ^6.4.1

  # Google Maps
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_webservice_ex: ^0.0.1+3

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.3

  # Local Storage
  shared_preferences: ^2.5.3

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  iconsax_flutter: ^1.0.1

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  cloud_functions: ^6.0.0
  cached_network_image: ^3.4.1
  flutter_vector_icons: ^2.0.0
  fl_chart: ^1.1.1

  # Object Detection
  onnxruntime: ^1.4.1

  # Web
  file_picker: ^10.3.6
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0

  #------------------ ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  #------------------ LOCAL ASSETS ------------------#
  assets:
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/user/
    - assets/logos/
    - assets/videos/
    - assets/models/

  #------------------ LOCAL FONTS ------------------#
  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Bold.ttf
          weight: 400
        - asset: assets/fonts/Rajdhani-Regular.ttf

  
  
