import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:fyp/data/repositories/achievement/achievement_repostory.dart';
import 'package:fyp/utils/popups/admin_loaders.dart';
import 'package:fyp/utils/popups/loaders.dart';
import '../../../leaderboard_achievement/models/achievement_level_model.dart';
import '../../../leaderboard_achievement/models/achievement_model.dart';

class EditAchievementController extends GetxController {
  final _achievementRepo = Get.put(AchievementRepository());

  // Observables
  final RxBool isLoading = false.obs;
  final RxBool isSaving = false.obs;
  late final Rx<Achievement> achievement;
  final RxList<AchievementLevel> editedLevels = <AchievementLevel>[].obs;
  final RxBool hasChanges = false.obs;
  final RxBool canSave = false.obs;

  @override
  void onInit() {
    super.onInit();
    final args = Get.arguments;
    if (args != null && args is Achievement) {
      achievement = args.obs;
      _initializeLevels();
    }

    // Monitor changes
    ever(editedLevels, (_) => _validateChanges());
  }

  void _initializeLevels() {
    // Deep copy of levels
    editedLevels.value = achievement.value.achievementLevels
        .map((level) => level.copyWith())
        .toList();
  }

  /// Update a specific field of a level
  void updateLevelField(int index, String field, dynamic value) {
    if (index < 0 || index >= editedLevels.length) return;

    final level = editedLevels[index];

    switch (field) {
      case 'badgeImage':
        editedLevels[index] = level.copyWith(badgeImage: value as String);
        break;
      case 'title':
        editedLevels[index] = level.copyWith(title: value as String);
        break;
      case 'description':
        editedLevels[index] = level.copyWith(description: value as String);
        break;
      case 'unlockCriteria':
        editedLevels[index] = level.copyWith(unlockCriteria: value as int);
        break;
    }

    hasChanges.value = true;
    _validateChanges();
  }

  /// Add a new level
  void addLevel() {
    if (editedLevels.length >= 7) {
      FAdminLoaders.warningSnackBar(
        title: 'Maximum Levels Reached',
        message: 'You can only have a maximum of 7 levels.',
      );
      return;
    }

    final newLevelNumber = editedLevels.length + 1;
    final previousLevel = editedLevels.isNotEmpty ? editedLevels.last : null;

    // Calculate minimum unlock criteria (25% more than previous level)
    final minUnlockCriteria = previousLevel != null
        ? (previousLevel.unlockCriteria * 1.25).ceil()
        : 10;

    final newLevel = AchievementLevel(
      achievementLevelId: '', // Will be generated by Firestore
      level: newLevelNumber,
      unlockCriteria: minUnlockCriteria,
      title: 'Level $newLevelNumber',
      description: 'Complete this level to progress further',
      badgeImage: '🏆',
    );

    editedLevels.add(newLevel);
    hasChanges.value = true;
    _validateChanges();
  }

  /// Remove a level
  void removeLevel(int index) {
    // 只有 Level 4 及后面的等级可以删除 (index >= 3 对应 Level 4)
    if (index < 3) {
      FAdminLoaders.warningSnackBar(
        title: 'Cannot Remove Level',
        message: 'You can only remove Level 4 and above. The first 3 levels are required.',
      );
      return;
    }

    // Show confirmation dialog
    Get.dialog(
      AlertDialog(
        backgroundColor: Get.isDarkMode
            ? const Color(0xFF111B2B)
            : Colors.white,
        title: Text(
          'Remove Level ${editedLevels[index].level}?',
          style: TextStyle(
            color: Get.isDarkMode
                ? const Color(0xFFE2E8F0)
                : const Color(0xFF32325D),
          ),
        ),
        content: Text(
          'Are you sure you want to remove this level? All subsequent levels will be renumbered.',
          style: TextStyle(
            color: Get.isDarkMode
                ? const Color(0xFF94A3B8)
                : const Color(0xFF8898AA),
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Get.back(),
            child: Text(
              'Cancel',
              style: TextStyle(
                color: Get.isDarkMode
                    ? const Color(0xFF94A3B8)
                    : const Color(0xFF8898AA),
              ),
            ),
          ),
          ElevatedButton(
            onPressed: () {
              Get.back();
              _performRemoveLevel(index);
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: Get.isDarkMode
                  ? const Color(0xFFFC7C8A)
                  : const Color(0xFFF5365C),
            ),
            child: const Text(
              'Remove',
              style: TextStyle(color: Colors.white),
            ),
          ),
        ],
      ),
    );
  }

  void _performRemoveLevel(int index) {
    // Remove the level at the specified index
    editedLevels.removeAt(index);

    // Create a new list with renumbered levels
    List<AchievementLevel> renumberedLevels = [];
    for (int i = 0; i < editedLevels.length; i++) {
      renumberedLevels.add(editedLevels[i].copyWith(level: i + 1));
    }

    // Replace the entire list to trigger UI update
    editedLevels.value = renumberedLevels;

    hasChanges.value = true;
    _validateChanges();
  }

  /// Get minimum unlock criteria for a level
  int getMinimumUnlockCriteria(int index) {
    if (index == 0) return 1;

    final previousLevel = editedLevels[index - 1];
    return (previousLevel.unlockCriteria * 1.25).ceil();
  }

  /// Validate all changes
  void _validateChanges() {
    bool isValid = true;
    String? errorMessage;

    // Check minimum levels
    if (editedLevels.length < 3) {
      isValid = false;
      errorMessage = 'Minimum 3 levels required';
    }

    // Check each level
    for (int i = 0; i < editedLevels.length; i++) {
      final level = editedLevels[i];

      // Check badge emoji is not empty
      if (level.badgeImage.trim().isEmpty) {
        isValid = false;
        errorMessage = 'Level ${level.level}: Badge emoji is required';
        break;
      }

      // Check title is not empty
      if (level.title.trim().isEmpty) {
        isValid = false;
        errorMessage = 'Level ${level.level}: Title is required';
        break;
      }

      // Check description is not empty
      if (level.description.trim().isEmpty) {
        isValid = false;
        errorMessage = 'Level ${level.level}: Description is required';
        break;
      }

      // Check unlock criteria
      if (level.unlockCriteria <= 0) {
        isValid = false;
        errorMessage = 'Level ${level.level}: Unlock criteria must be greater than 0';
        break;
      }

      // Check 25% increase for levels after first
      if (i > 0) {
        final previousLevel = editedLevels[i - 1];
        final minCriteria = (previousLevel.unlockCriteria * 1.25).ceil();

        if (level.unlockCriteria < minCriteria) {
          isValid = false;
          errorMessage =
          'Level ${level.level}: Unlock criteria must be at least $minCriteria (25% more than previous level)';
          break;
        }
      }
    }

    canSave.value = isValid && hasChanges.value;

    // Show error if validation failed
    if (!isValid && errorMessage != null && hasChanges.value) {
      Future.delayed(const Duration(milliseconds: 100), () {
        if (!canSave.value && hasChanges.value) {
          FAdminLoaders.customToast(message: errorMessage);
        }
      });
    }
  }

  /// Save changes to Firestore
  Future<void> saveChanges() async {
    if (!canSave.value) return;

    // 显示确认对话框
    FAdminLoaders.showAchievementUpdateDialog(
      changedFields: _getChangedFields(),
      onConfirm: () async {
        try {
          isSaving.value = true;
          FLoaders.showLoading('Saving changes...');

          // Update achievement in Firestore
          await _achievementRepo.updateAchievementWithLevels(
            achievementId: achievement.value.achievementId,
            levels: editedLevels,
          );

          FLoaders.stopLoading();

          FAdminLoaders.successSnackBar(
            title: 'Success',
            message: 'Achievement updated successfully',
          );

          Get.back(); // 关闭编辑对话框
        } catch (e) {
          print('$e');
          FLoaders.stopLoading();
          FAdminLoaders.errorSnackBar(
            title: 'Error',
            message: 'Failed to update achievement: $e',
          );
        } finally {
          isSaving.value = false;
        }
      },
    );
  }

  /// 获取更改的字段列表
  List<String> _getChangedFields() {
    final List<String> changes = [];

    // 检查等级数量变化
    if (editedLevels.length != achievement.value.achievementLevels.length) {
      changes.add('Number of levels (${achievement.value.achievementLevels.length} → ${editedLevels.length})');
    }

    // 检查每个等级的变化
    for (int i = 0; i < editedLevels.length; i++) {
      final editedLevel = editedLevels[i];
      final originalLevel = i < achievement.value.achievementLevels.length
          ? achievement.value.achievementLevels[i]
          : null;

      if (originalLevel == null) {
        changes.add('Added Level ${editedLevel.level}');
        continue;
      }

      // 检查具体字段变化
      if (editedLevel.title != originalLevel.title) {
        changes.add('Level ${editedLevel.level} title');
      }
      if (editedLevel.description != originalLevel.description) {
        changes.add('Level ${editedLevel.level} description');
      }
      if (editedLevel.badgeImage != originalLevel.badgeImage) {
        changes.add('Level ${editedLevel.level} badge');
      }
      if (editedLevel.unlockCriteria != originalLevel.unlockCriteria) {
        changes.add('Level ${editedLevel.level} unlock criteria (${originalLevel.unlockCriteria} → ${editedLevel.unlockCriteria})');
      }
    }

    return changes;
  }
}